### ISSUE TITLE
Plans for VRT - Week 6

### ISSUE THREAD

**Issue by muniter** [muniter/e2e_testing_assignment#2]
## TODO  (Internal process)

Para hacer trabajo de regresión visual correremos dos versiones, `4.35` y la `4.41`.

Entre estas dos versiones hay una cantidad considerable de regresión visual pero nuestros test pasan en su gram mayoría. Solo los siguientes se deben arreglar:

Ambas:

P: Playwright
K: Kraken

- (P, K) Hacer el setup (primer login) del sitio (la interfaz es un tanto distinta).
- (P, K) Delete member
- (P) Filter member remove label

## Refactors:

- [x] Extract setup logic to be shared between versions.
- [x] Try to save the session cookie instead of login every time or handle it by otherwise

## New features

- [x] Seed faker (maybe share it) to always produce the same output essential for VRT
- [x] Environment must be the same for both runs now, so order of tests is needed, otherwise clean database wipe for every test case. (maybe worth wiping to keep the parallel execution of playywright?, or meh not worth it?)
- [x] For this use case perhaps docker should be preferred It's so easy to dispose, if we are all using Linux.

## Reports

- Investigate how playwright and when does it take screenshots, the steps in which it takes the screenshot might be needed, a good guide could be de feature files steps, take a screenshot in each.

- Make both share the same interface, for example in each step it tracks a screenshot, a URL, etc ideally to produce something like:

```json
{
  "scenario": "Create a member",
  "ghost_version": 4.41,
  "steps": [
    "login": {
      "url": "http://something",
      "image": "/path/to/bla/bla/login.png"
    },
    "create member open": {
      "url": "http://something",
      "image": "/path/to/bla/bla/create member open.png"
    }
  ]
}
```

So we make both Ghost and Playwright produce the same output at the end, and the comparison tool we use then processes them the same exact way.

CC: @htenezaca @Andesjavierleon

**Comment by htenezaca** [comment]
We completed all proposed tasks.
